apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition 
metadata:
  name: databases.example.com 
spec:
  group: example.com         # API Group 
  scope: Namespaced          # (NamedSpaced or Clusterwide)
  names:
    plural: databases        # Plural Name (used in `kubectl get databases`)
    singular: database       # Singular Name
    kind: Database           # Kind (like Deployment or Pod)\
    shortNames: 
      - db                   # Short alias (`kubectl get db`)

  versions:
    - name: v1 
      served: true 
      storage: true
      schema:
        openAPIV3Schema:
          type: object 
          properties:
            spec:
              type: object
              properties:
                engine:
                  type: string 
                version:
                  type: string 
