apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 30160225/nginx-image-demo:v1 # Update the image for testing
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name:  demo-secret