apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      resources:
        requests:
          memory: "1Gi"  # Exceeds the ResourceQuota limit of 2Gi
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1"
