apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: jenkins-pv-claim 
  namespace: jenkins 
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi

  