apiVersion: v1 
kind: Secret 
metadata:
  name: sa-token-cert 
  namespace: jenkins 
  annotations:
    kubernetes.io/service-account.name: jenkins-admin 
    type: kubernetes.io/service-account-token

