steps:
  # build the container image
- id: Build the image
  name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - ${_IMAGE}
    - .

# Push the built image to the container registry service
- id: Push the image to container registry
  name: gcr.io/cloud-builders/docker
  args:
    - push
    - ${_IMAGE}

  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=manifest.yaml
  - --image=${_IMAGE}
  - --location=${_REGION}
  - --cluster=${_CLUSTER_NAME}

# Here are the substitution variables related to the services.
substitutions:
  _REGION: us-central1 # The region where the cloud services are located.
  _APP_NAME: node-web-app
  _CLUSTER_NAME: gke-public-cluster
  _IMAGE: gcr.io/$PROJECT_ID/${_APP_NAME}:${BUILD_ID}-${COMMIT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY

# The structure of the built image
images:
  - ${_IMAGE}